# Generated by Django 4.2.6 on 2025-05-17 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("INACTIVE", "INACTIVE"),
                    ("DELETED", "DELETED"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="entity_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="entity_type",
            field=models.CharField(
                choices=[("client", "client"), ("partner", "partner")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="environment",
            field=models.CharField(default="test", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("INACTIVE", "INACTIVE"),
                    ("DELETED", "DELETED"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PartnerInfo",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("logo", models.URLField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "partner_info",
            },
        ),
        migrations.CreateModel(
            name="ClientInfo",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("role", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "client_info",
            },
        ),
    ]
